openapi: 3.0.3
info:
  title: Prompt Management API
  version: 0.1.0
servers:
  - url: https://apisix.dev.hgenai.gl
    description: Apisix API
  - url: https://apisix.qa.hgenai.gl
    description: Apisix API
  - url: http://localhost:8081
    description: Apisix local API
security:
  - OIDC-DEV: []
  - OIDC-QA: []
paths:
  /v1/prompt_templates:
    get:
      tags:
        - Public Prompts
      summary: Get Prompt Templates
      operationId: get_prompt_templates
      parameters:
        - in: header
          name: Authorization
          description: Authorization Bearer token
          schema:
            type: string
        - name: intent
          in: query
          required: false
          schema:
            anyOf:
              - type: string
                format: uuid
                nullable: true
            title: Intent
        - name: accelerator
          in: query
          required: false
          schema:
            anyOf:
              - type: string
                format: uuid
                nullable: true
            title: Accelerator
        - name: locale
          in: query
          required: false
          schema:
            anyOf:
              - type: string
                format: uuid
                nullable: true
            title: Locale
        - name: model
          in: query
          required: false
          schema:
            anyOf:
              - type: string
                format: uuid
                nullable: true
            title: Model
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: uuid
                title: Response Get Prompt Templates Api V1 Prompt  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/prompt_templates/{prompt_id}:
    get:
      tags:
        - Public Prompts
      summary: Get Prompt Template
      operationId: get_prompt_template

      parameters:
        - name: prompt_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            title: Prompt Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PromptTemplateWithVariables'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/tags:
    get:
      tags:
        - Public Tags
      summary: Get Tag Categories With Tags
      operationId: get_tag_categories
      parameters:
        - name: requester
          in: query
          required: false
          schema:
            anyOf:
              - type: string
                nullable: true
            title: Requester
        - name: type
          in: query
          required: false
          schema:
            allOf:
              - $ref: '#/components/schemas/TagsType'
            title: Type
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TagCategoryWithTags'
                title: Response Get Tag Categories With Tags Api V1 Tag Category  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  securitySchemes:
    OIDC-DEV:
      type: openIdConnect
      openIdConnectUrl: https://apisix.dev.hgenai.gl/auth/realms/dev/.well-known/openid-configuration
    OIDC-QA:
      type: openIdConnect
      openIdConnectUrl: https://apisix.qa.hgenai.gl/auth/realms/genai/.well-known/openid-configuration
  schemas:
    BindingType:
      type: string
      enum:
        - constant
        - query
        - rag-content
        - history
        - app_variable
      title: BindingType
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    PromptTemplateVariable:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        name:
          type: string
          title: Name
        description:
          anyOf:
            - type: string
              nullable: true
          title: Description
        required:
          type: boolean
          title: Required
        data_type:
          type: string
          title: Data Type
        binding_type:
          $ref: '#/components/schemas/BindingType'
        binding_value:
          anyOf:
            - type: string
              nullable: true
          title: Binding Value
      type: object
      required:
        - id
        - name
        - description
        - required
        - data_type
        - binding_type
        - binding_value
      title: PromptTemplateVariable
    PromptTemplateWithVariables:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        body:
          type: string
          title: Body
        variables:
          items:
            $ref: '#/components/schemas/PromptTemplateVariable'
          type: array
          title: Variables
      type: object
      required:
        - id
        - body
        - variables
      title: PromptTemplateWithVariables
    Tag:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        name:
          type: string
          title: Name
        description:
          type: string
          title: Description
        active:
          type: boolean
          title: Active
        created_date:
          type: string
          format: date-time
          title: Created Date
      type: object
      required:
        - id
        - name
        - description
        - active
        - created_date
      title: Tag
    TagCategoryWithTags:
      properties:
        id:
          type: string
          format: uuid
          title: Id
        name:
          type: string
          title: Name
        description:
          type: string
          title: Description
        type:
          $ref: '#/components/schemas/TagsType'
        active:
          type: boolean
          title: Active
        color:
          type: string
          title: Color
        icon:
          type: string
          title: Icon
        created_date:
          type: string
          format: date-time
          title: Created Date
        tags:
          items:
            $ref: '#/components/schemas/Tag'
          type: array
          title: Tags
      type: object
      required:
        - id
        - name
        - description
        - type
        - active
        - color
        - icon
        - created_date
        - tags
      title: TagCategoryWithTags
    TagsType:
      type: string
      enum:
        - system
        - custom
      title: TagsType
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError