openapi: 3.0.0
info:
  title: ContentHub API specification
  version: 1.0.0
security:
  - OIDC-DEV: []
  - OIDC-QA: []
paths:
  /metadata:
    get:
      summary: Get a list of distinct metadata
      operationId: getMetadata
      tags:
        - Metadata
      responses:
        '200':
          description: Successfully retrieved list of Metadata Tags
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MetadataInfo'
        '500':
            description: Unexpected processing error. The request can be re-submitted to the processing
            headers: {}
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/errorMessage'
  /metadata/tags:
    get:
      summary: Get a list of distinct tags
      operationId: getTags
      tags:
        - Metadata

      responses:
        '200':
          description: Successfully retrieved list of tags
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '500':
            description: Unexpected processing error. The request can be re-submitted to the processing
            headers: {}
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/errorMessage'
components:
  schemas:
    errorMessage:
      type: object
      properties:
        errorText:
          type: string
    MetadataInfo:
      type: object
      properties:
        id:
          type: string
        tag:
          type: string
        description:
          type: string
        componentSource:
          type: string
        isOptional:
          type: boolean
  securitySchemes:
    OIDC-DEV:
      type: openIdConnect
      openIdConnectUrl: http://internal.keycloak.dev.hgenai.gl:8085/auth/realms/dev/.well-known/openid-configuration
    OIDC-QA:
      type: openIdConnect
      openIdConnectUrl: https://apisix.qa.hgenai.gl/auth/realms/genai/.well-known/openid-configuration
