site_name: 'Sample API documentation'
repo_url: https://github.com/yehorkovalchuk777/techdocs-test

nav:
  - Home: index.md
  - Endpoints: endpoints.md
  - 'CI pipeline': ci-pipeline.md

plugins:
  - techdocs-core
