openapi: 3.1.0
info:
  title: Sample API
  description: |-
    This is a sample api based on the OpenAPI 3.1 specification

  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://apisix.dev.hgenai.gl
    description: Apisix API
  - url: https://apisix.qa.hgenai.gl
    description: Apisix API
  - url: http://localhost:8081
    description: Apisix local API
security:
  - bearerAuth: [ ]
paths:
  https://apisix.dev.hgenai.gl/auth/realms/dev/protocol/openid-connect/token:
    post:
      summary: Authorize [DEV]
      operationId: auth
      tags:
        - Authorization
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/KeycloakLoginRequest'
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
  https://apisix.qa.hgenai.gl/auth/realms/qa/protocol/openid-connect/token:
    post:
      summary: Authorize [QA]
      operationId: auth
      tags:
        - Authorization
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/KeycloakLoginRequest'
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
  /v1/test:
    get:
      summary: test-v1
      operationId: test-v1
      tags:
        - API
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
  /v2/test:
    get:
      summary: test-v2
      operationId: test-v2
      tags:
        - API
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
  /headers:
    get:
      summary: headers
      operationId: headers
      tags:
        - API
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    headerName:
                      type: string
                    headerValues:
                      type: array
                      items:
                        type: string
components:
  schemas:
    KeycloakLoginRequest:
      type: object
      properties:
        grant_type:
          type: string
          default: password
        client_id:
          type: string
        client_secret:
          type: string
          format: password
        username:
          type: string
        password:
          type: string
          format: password
      required:
        - grant_type
        - client_id
        - client_secret
        - username
        - password
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
