openapi: 3.0.3
info:
  title: Grounding Hub REST API
  version: 0.0.3
servers:
  - url: https://apisix.dev.hgenai.gl
    description: Apisix API
security:
  - openId: []
paths:
  /v1/chat/completions:
    post:
      tags:
        - Completion Generation
      summary: >-
        Returns result of LLM inference on the given query (with optional use of
        the knowledge database)
      operationId: chat_completion
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatCompletionRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatCompletionResponse'
  /v1/direct/completions:
    post:
      tags:
        - Completion Generation
      summary: >-
        Returns result of direct call to the LLM on the given query. No addtional
        query transformations are applied
      operationId: direct_completion
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DirectCompletionRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DirectCompletionResponse'
components:
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://apisix.dev.hgenai.gl/auth/realms/dev/.well-known/openid-configuration
  schemas:
    ChatCompletionRequest:
      type: object
      properties:
        query:
          description: The query from the client app
          type: string
          example: Show me mounthly income in the form of table for the last quater
        messages:
          description: Chat history
          type: array
          items:
            type: object
            additionalProperties:
              $ref: '#/components/schemas/Message'
          default: []
          example:
            - role: user
              content: Hello!
            - role: assistant
              content: Good morning. How can I assist you?
        rag_config:
          $ref: '#/components/schemas/RAGConfig'
        prompt_config:
          $ref: "#/components/schemas/PromptConfig"
        model_settings:
          $ref: '#/components/schemas/ModelSettings'
      required:
        - query
    ChatCompletionResponse:
      type: object
      properties:
        completion:
          description: Response from the GroundingHub
          type: string
          example: >-
            Sure, here is incomes for the last 4 three for the Hitach GenAI
            Platform project: ...
        documents:
          description: Documents, retrieved by RAG
          type: array
          items:
            $ref: '#/components/schemas/Document'
        model:
          description: >-
            Model used for completion generation. If the model has been
            provided in the response (see _model_settings->model_ field of the
            request), then should be equal to the provided value, is set.
          type: string
          example: gpt-4-32k
          nullable: true
          default: null
      required:
        - completion
    DirectCompletionRequest:
      type: object
      properties:
        prompt:
          description: The query from the client app
          type: string
          example: Show me mounthly income in the form of table for the last quater
        model_settings:
          $ref: '#/components/schemas/ModelSettings'
      required:
        - prompt
    DirectCompletionResponse:
      type: object
      properties:
        completion:
          description: Response from the GroundingHub
          type: string
          example: >-
            Sure, here is incomes for the last 4 three for the Hitach GenAI
            Platform project: ...
        model:
          description: >-
            Model used for completion generation. If the model has been
            provided in the response (see _model_settings->model_ field of the
            request), then should be equal to the provided value, is set.
          type: string
          example: gpt-4-32k
          nullable: true
          default: null
      required:
        - completion
    Error:
      type: object
      properties:
        code:
          description: >-
            Error code. Could be used by the client app to handle the error
            properly
          type: string
          example: 400
        message:
          description: >-
            Error message. Could be used by the client app to handle the error
            properly
          type: string
          example: Invalid request
    Message:
      type: object
      properties:
        role:
          description: >-
            Role of the message sender. Used by LLM to
            distinguish between system and user, and
            ai (assistant) messages
          type: string
          enum:
            - system
            - user
            - assistant
        content:
          description: >-
            Message content. Currently only text messages are
            supported
          type: string
      required:
        - role
        - content
      example: {role: "user", content: "Please, tell me about the human rights"}
    RAGConfig:
      type: object
      properties:
        document_properties:
          description: >-
            Required documents properties to filter documents. Each key corresponds to a separate property.
            The values should be an array of strings, where each element of the array
            describes the single matching rule, and all rules are combined
            via OR logical operation.
            If not set or ```null``` then all allowed documents will be used.
          type: object
          additionalProperties:
            type: array
            items:
              type: string
            default: []
          nullable: true
          default: null
          example:
            organization:
              - hitachi-rail
            document_class:
              - manual
              - user-manual
            language:
              - english
            content_type:
              - schematics
    PromptConfig:
      type: object
      properties:
        template_id:
          description: >-
            ID of the template required to be used to build prompt
          type: string
        input_variables:
          description: >-
            Dictionary (key => value) of variables to be bind with the
            template
          type: object
          nullable: true
          additionalProperties:
            type: string
          example:
            speciality: "computer engineer"
            age: "34"
          default: null
      required:
        - template_id
    ModelParams:
      type: object
      properties:
        temperature:
          description: >-
            Temperature value for the top-p sampling. The higher the value, the
            more random the output. Lower values leads to generation of
            more focused and deterministic completions. It is suggested to
            alter this of ```top_p```, but not both.
            If not set or ```null``` then the default value for the
            corresponding model will be used.
          type: number
          nullable: true
          minimum: 0
          maximum: 2
          default: null
          example: 0.9
        top_p:
          description: >-
            Sample from tokens with ```top_p``` probability mass,
            e.g. 0.2 means only the tokens comprising the
            top 20% probability mass are considered, while 1.0
            means all tokens will be considered. The higher the
            value, the more random the output.
            If not set or ```null``` then the default value for
            the corresponding ```model``` will be used.
            It is suggested to alter this of ```temperature```,
            but not both.
          type: number
          nullable: true
          minimum: 0
          maximum: 1
          default: null
          example: 0.1
        max_tokens:
          description: >-
            Maximum number of tokens to generate. The higher the value, the more
            random the output. The total length of input tokens and generated
            tokens is limited by the model's context length. Zero value means max
            possible number of tokens.
          type: integer
          minimum: 0
          default: 16
          example: 100
        stop:
          description: >-
            List of sequences where the API will stop generating further tokens. The supported number of sequences depends on the model.
          type: array
          items:
            type: string
          nullable: true
          default: null
          example: ['stop', '\n', 'user:']
    ModelSettings:
      type: object
      properties:
        model:
          description: ID of the model to use for inference
          type: string
          example: hitachi-genai-platform/HGP-7b-instruct
        params:
          $ref: '#/components/schemas/ModelParams'
      required:
        - model
    Position:
      type: object
      description: Position of the current data in the original document
      properties:
        offset:
          description: >-
            Offset of the current data from the beginning of the
            original document. Units depends on the document type,
            e.g. could be characters for text documents
          type: integer
          minimum: 0
          example: 1233
        length:
          description: >-
            Length of the data. Units depends on the document
            type, e.g. could be characters for text documents
          type: integer
          minimum: 0
          example: 354
      required:
        - offset
        - length
    Author:
      description: Information about document author
      type: object
      properties:
        name:
          description: Author name
          type: string
        email:
          description: Contact e-mail
          type: string
          format: email
      required:
        - name
    DocumentMetadata:
      type: object
      description: Information about the source document and the current data
      properties:
        source_mime_type:
          description: Type of the source document, e.g., application/pdf, text/csv, application/vnd.youtube.yt (see https://www.iana.org/assignments/media-types/media-types.xhtml)
          type: string
          example: application/pdf
        title:
          description: Title of the document, if available
          type: string
          example: Quater financial report
        authors:
          description: >-
            List of authors of the document
          type: array
          items:
            $ref: "#/components/schemas/Author"
        mime_type:
          description: Type of the data, e.g., text/plain, video/3gpp, image/png (see https://www.iana.org/assignments/media-types/media-types.xhtml)
          type: string
          example: text/plain
        url:
          description: URL to the original document
          type: string
          format: uri
          example: >-
            https://hitachi-doc.com/public/reports/879asjalsasf9913.pdf
        created:
          description: >-
            Source document creation date-time. the date-time notation as defined by RFC 3339, section 5.6, for example, 2023-07-21T17:32:28Z
          type: string
          format: date-time
          example: 2023-07-21T17:32:28Z
        tags:
          description: >-
            List of tags assigned to the source document (see ```RAGConfig.document_tags```).
          type: array
          items:
            type: string
          example:
            - public
            - financial
            - hitachi-genai-platform
        position:
          $ref: '#/components/schemas/Position'
      anyOf:
        - required:
            - title
            - url
        - required:
            - title
            - url
            - position
            - mime_type
    Document:
      description: Document, retrieved by RAG
      type: object
      properties:
        similarity:
          description: >-
            Similarity value between the user request and current data. Could be
            interpreted as relevance for some cases
          type: number
          minimum: 0
          maximum: 1
          default: 0
          example: 0.97
        metadata:
          $ref: '#/components/schemas/DocumentMetadata'
        content:
          type: object
          description: >-
            Optional document content. The type depends on the data type, and can
            be string for text data or binary for files
          oneOf:
            - type: string
            - type: string
              format: binary
          example: Here some data extracted from the document...
      required:
        - metadata
