openapi: 3.1.0
info:
  title: Sample API
  description: |-
    This is a sample api based on the OpenAPI 3.1 specification

  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

servers:
  - url: http://localhost:8081
    description: Apisix forwarded server

paths:
  /v1/test:
    get:
      summary: test-v1
      security:
        - openId: []
      operationId: test-v1
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
  /v2/test:
    get:
      summary: test-v2
      security:
        - openId: []
      operationId: test-v2
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
  /headers:
    get:
      summary: headers
      security:
        - openId: []
      operationId: headers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    headerName:
                      type: string
                    headerValues:
                      type: array
                      items:
                        type: string
components:
  schemas:
    Sample:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: john
  securitySchemes:
    openId:   # <--- Arbitrary name for the security scheme. Used to refer to it from elsewhere.
      type: openIdConnect
      openIdConnectUrl: http://localhost:8081/realms/dev/.well-known/openid-configuration
