openapi: 3.1.0
info:
  title: Sample API
  description: |-
    This is a sample api based on the OpenAPI 3.1 specification

  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://apisix.dev.hgenai.gl
    description: Apisix API
  - url: https://apisix.qa.hgenai.gl
    description: Apisix API
  - url: http://localhost:8081
    description: Apisix local API
security:
  - OIDC-DEV: []
  - OIDC-QA: []
paths:
  /v1/test:
    get:
      summary: test-v1
      operationId: test-v1
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
  /v2/test:
    get:
      summary: test-v2
      operationId: test-v2
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
  /headers:
    get:
      summary: headers
      operationId: headers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    headerName:
                      type: string
                    headerValues:
                      type: array
                      items:
                        type: string
components:
  securitySchemes:
    OIDC-DEV:
      type: openIdConnect
      openIdConnectUrl: https://apisix.dev.hgenai.gl/auth/realms/dev/.well-known/openid-configuration
    OIDC-QA:
      type: openIdConnect
      openIdConnectUrl: https://apisix.qa.hgenai.gl/auth/realms/genai/.well-known/openid-configuration
