openapi: 3.1.0
info:
  title: Sample API
  description: |-
    This is a sample api based on the OpenAPI 3.1 specification

  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

servers:
  - url: http://localhost:8081
    description: Apisix API

paths:
  http://10.6.0.207:8085/auth/realms/dev/protocol/openid-connect/token:
    post:
      summary: auth
      operationId: auth
      parameters:
        - in: header
          name: Host
          schema:
            type: string
            default: keycloak-http.keycloak-auth:8085
          required: true
      requestBody:
        required: true
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  grant_type:
                    type: string
                    default: password
                  client_id:
                    type: string
                    default: dev
                  client_secret:
                    type: string
                  username:
                    type: string
                  password:
                    type: string
                required:
                  - grant_type
                  - client_id
                  - client_secret
                  - username
                  - password
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
  /v1/test:
    get:
      summary: test-v1
      security:
        - openId: []
      operationId: test-v1
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
  /v2/test:
    get:
      summary: test-v2
      security:
        - openId: []
      operationId: test-v2
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
  /headers:
    get:
      summary: headers
      security:
        - openId: []
      operationId: headers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    headerName:
                      type: string
                    headerValues:
                      type: array
                      items:
                        type: string
components:
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: http://localhost:8081/realms/dev/.well-known/openid-configuration
